## import lib

In [1]:
import numpy as np


## declare scalar , vector, matrices

## Scalars

In [2]:
s = 5
s

5

## vector

In [3]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

## Matrices

In [4]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data Types

In [5]:
type(s)

int

In [6]:
type(v)

numpy.ndarray

In [7]:
type(m)

numpy.ndarray

In [8]:
s_array = np.array(5)
s_array

array(5)

## Data shapes

In [10]:
m.shape

(2, 3)

## creating a column vector

In [12]:
v.shape


(3,)

In [13]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [14]:
v.shape

(3,)