## Train Test Split

## import relevant libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [3]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## split the data

In [5]:
train_test_split(a)

[array([100,  34,  90,  17,  46,  86,  82,  44,  94,  31,  38,  24,  37,
         32,   6,  81,  72,  97,  21,   9,  49,  99,  77,  43,  36,  18,
         42,  39,  83,  79,  51,  91,  35,  87,  41,  14,  78,   4,   1,
         55,  62,  66,  85,  33,  80,  96,  56,  92,  12,  53,  48,  58,
         27,  89,  25,  28,  69,   7,  30,  61,  63,  10,   5,  73,  76,
         29,  75,  67,  16,  88,  64,  50,   3,  71,  20]),
 array([26, 11, 60, 95, 45, 93, 68, 54, 52,  8, 47, 40, 19, 98, 15, 23, 84,
        74, 65, 57,  2, 22, 13, 70, 59])]

In [19]:
a_train,a_test = train_test_split(a,test_size=0.2,random_state=42)

## explore the result

In [20]:
a_train.shape , a_test.shape

((80,), (20,))

In [21]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [22]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [24]:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2)

In [25]:
a_train.shape,a_test.shape

((80,), (20,))

In [26]:
b_train.shape,b_test.shape

((80,), (20,))